version: '3'

services:
  server:    
    build:
      context: server
      dockerfile: Dockerfile
    image: "node-graphql-server"
    ports:
      - "5000:5000"
  client:
    build:
      context: client
      dockerfile: Dockerfile
    image: "react-client"
    ports:
      - "3000:3000"
  